blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/n-ae/confytome#readme
    about: Check the README for documentation and examples
  - name: Discussions
    url: https://github.com/n-ae/confytome/discussions
    about: Ask questions and discuss ideas with the community